# This file was generated automatically from conda-smithy. To update this configuration,
# update the conda-forge.yaml and/or the recipe/meta.yaml.

language: objective-c

env:
  matrix:
    
    - CONDA_PY=27
    - CONDA_PY=34
    - CONDA_PY=35
  global:
    # The BINSTAR_TOKEN secure variable. This is defined canonically in conda-forge.yml.
    - secure: "QLnDDq9Z7b9ox65zIcDc2CHfnuxzEO+92fKgglhs6mj6/YfyzFdeF5bAy+vk7MCz3Xc1ubCujNSp6+D+hjNKy9nUZPTk294x6oFMkFVVWCTeCWrXuihNRQErWIKkelXe78XIK7KtalPrLi89Yfdn+RI/pqd/+WdZPp9qnwMg/RwQcyvSlRLoEEp+hwD6NVkBKPGVng1ZD3FODjmKXTnQlrF10U1sXALy6DDQb43CvS+zvKsKgbfn5K/POEblx+ftuQi3BKixQXMNx6XP/W/oSqYMjUa3LYMIkrWHlr/JqcPRaOUMvscGPWjwdKKL87WEarlqxpEKJOGYi5/MUs+uSVXRLBp8v/unYkcVGhww5oN031ZLUgXcJ4zlCclwWFtDrgX/DyZEWn/TAQH8QS+co+iHKC/YRT1dJ8ycv9WgCjTuXtm4pbYL1S4WO3/aS0JVo/2p2XFsh39IO5iACUGL/EclVqkdIDIHOaCZE1WOXqEq5x7VrHBPxdYdJorn7le+XK5aW7s+VIskgBnXbs7Z3rDyThXYbWOPq2TNgpNjka4lEJI92fAu28Fbaiuja7rmu0dXE6l0AVHxplKAL3l0nT+A+cBJeNm31q6hStD60xvnZmaqFG8iZ8eJ6lPhJc/IOLtrdmus3g1SO0K9WpPWevrXvNvkEuc/6Pw8yKRfaI0="


before_install:
    # Remove homebrew.
    - brew remove --force $(brew list)
    - brew cleanup -s
    - rm -rf $(brew --cache)

install:
    - |
      MINICONDA_URL="http://repo.continuum.io/miniconda"
      MINICONDA_FILE="Miniconda3-latest-MacOSX-x86_64.sh"
      curl -O "${MINICONDA_URL}/${MINICONDA_FILE}"
      bash $MINICONDA_FILE -b

      export PATH=/Users/travis/miniconda3/bin:$PATH

      conda config --set show_channel_urls true
      conda update --yes conda
      conda install --yes conda-build=1.20.0 jinja2 anaconda-client
      conda config --add channels conda-forge
      

script:
  - conda build ./recipe

after_success:

  - ./ci_support/upload_or_check_non_existence.py ./recipe conda-forge --channel=main
