travis:
  secure:
    BINSTAR_TOKEN: QLnDDq9Z7b9ox65zIcDc2CHfnuxzEO+92fKgglhs6mj6/YfyzFdeF5bAy+vk7MCz3Xc1ubCujNSp6+D+hjNKy9nUZPTk294x6oFMkFVVWCTeCWrXuihNRQErWIKkelXe78XIK7KtalPrLi89Yfdn+RI/pqd/+WdZPp9qnwMg/RwQcyvSlRLoEEp+hwD6NVkBKPGVng1ZD3FODjmKXTnQlrF10U1sXALy6DDQb43CvS+zvKsKgbfn5K/POEblx+ftuQi3BKixQXMNx6XP/W/oSqYMjUa3LYMIkrWHlr/JqcPRaOUMvscGPWjwdKKL87WEarlqxpEKJOGYi5/MUs+uSVXRLBp8v/unYkcVGhww5oN031ZLUgXcJ4zlCclwWFtDrgX/DyZEWn/TAQH8QS+co+iHKC/YRT1dJ8ycv9WgCjTuXtm4pbYL1S4WO3/aS0JVo/2p2XFsh39IO5iACUGL/EclVqkdIDIHOaCZE1WOXqEq5x7VrHBPxdYdJorn7le+XK5aW7s+VIskgBnXbs7Z3rDyThXYbWOPq2TNgpNjka4lEJI92fAu28Fbaiuja7rmu0dXE6l0AVHxplKAL3l0nT+A+cBJeNm31q6hStD60xvnZmaqFG8iZ8eJ6lPhJc/IOLtrdmus3g1SO0K9WpPWevrXvNvkEuc/6Pw8yKRfaI0=
appveyor:
  secure:
    BINSTAR_TOKEN: MP4hZYylDyUWEsrt3u3cod2sbFeRwUziH02mvQOdbjsTO/l1yIxDkP/76rSIjcGC
