travis:
  secure:
    BINSTAR_TOKEN: sWVDyvjPe+T6iTWWh3dNc1wz1tQTiGpS50216d80SStp/DzQgU6A84jn2J1jPcxlokUMxXb4k5ru8YF2fwXdcADRfarTYHUjiv+hWV+ERF0i7M8r29xNfgMpZFbURhwU44ReE20dB22d2ftFQ33N4MZ8zofgLhdmefN4xIqX4f7nOwuNLgi/Pdgai5MMD3whK6kCSsx0f/L4Zys/kfd8ri5LqtP/RGLHB+TVzE86S4mXpK8xtB/cvS4pcIzPeo7/ENM+AtjAuebPD0977Nz3a4+Y+ubWIiAyOBjqx177PjMj1tQ5hGjtTB4MCb+jfez6qgGvWOK1KKeJh2VTBK1tGpX8g5bvmt//RizB18wQirEBB4X1X6Z/CnK7mw+N5QgnCd2TsK/vhxLA7sXvMXpOt5Tcmx1pZ2BwFo70C4MmEbna3fhwcXqGiz0JoZx35vAVxdnPQmby3ik2svr8VPzdDkfqV+obPOrI1Oyx4Du1g9aT70OkzVVfUk0e6nx1VHKaw2Qu/SDUjUBULdjE9M56+T64yxHd373w4jl1EUTMLg94/9jnl/zcD6BPFcszod+B37Fht2AwzOn2Lp4PytF+5tCFACSaRX9skgOG3/v3NMlvyVuam14sc9C+38hi2t7sG3q0Ac8BG/RejyduSgjmmvVCegGI3B2fc4dLLNDd2ko=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
