travis:
  secure:
    BINSTAR_TOKEN: 0e+235u1nSywuSm6LRlCI6G23yvDABF8iX48lhA0AtTn5QDR/pAEDB96XHiKftWdr2HigZOyGWjlPoGs/HIpfWdJUcYo+trbQTxVvwZx88nDF6cNHpQCNG501lD3cSPfgAUmb7YiQMxS+orqsIfB4ar75AocBFZ/3qo9N7YByBFkPXc2fUD2UI7Ial4ugTEO6TbSIBVnFYAcDZiSLyse66D9N9XERqCCziVJoyskFLi6C+xoz/aqX+NYcL4d2DxoDRSl/070eOmrDnWIYcoVtN9eIlO5pFFEPWoxxXf+gJuY9bUmUNjUMjnT5/8ev0HiUzs8irbdyBb+ujR7HNXSB7UJtNDKUNz1Fc07/J5LdNdBZ5kghuA/SYOdBVOjlX6KIRVGHyNIaT8jDlK/rCFwVuNC1rDh8Z85rvJfwEz1iFDJHvk7NYM0YFze3ilzkpZq4Uy7HnPY8cTBzRoWiWQ0MwRei8w38wBFgkttuYAlzkMFFFuTZhtA62ZiTPzYcZL7ryYGQ9uYwQdCr3JlYP2MEQNC5klQaoZNsUHjxBJqQIRyPiiHQ/mC74Lf4zjGfJ48hFBFKAXWvVnBNKetFPoMTS7fIgHVpt3yxxY1nuNBgu0GrWHok5EQXyRbmPKhS1D76YeRdHAflsrBY10SZD4/w0QXLsa8Z+G+96s+xlZqFZ8=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
